version: '3.6'

services:

  database:
    image: postgres:10.4
    ports:
      - "0:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:4.0.9
    ports:
      - "0:6379"

  channeler: &base
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=settings.local
      - PGDATABASE=postgres
      - PGUSER=postgres
    #   - PGPASSWORD=pAssw0rd!
      - PGHOST=database_1
    #   - PGPORT=5432
      - REDIS_URL=redis://redis_1:6379
    volumes: 
      - .:/code

  channeler_app:
    <<: *base
    ports:
      - "8000:8000"

  channeler_worker:
    <<: *base
    command: bash -c 'python manage.py rqworker'

volumes:
  postgres_data:
